AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  process

  Sample SAM Template for process

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProcessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: process.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Layers:
      - !Ref Shared

  Shared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sm_shared
      ContentUri: '../target/shared.zip'
      Description: Dependencies for the Source Monitoring
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProcessFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/process"
  ProcessFunction:
    Description: "Process Lambda Function ARN"
    Value: !GetAtt ProcessFunction.Arn
  ProcessFunctionIamRole:
    Description: "Implicit IAM Role created for Process function"
    Value: !GetAtt ProcessFunctionRole.Arn
